
CREATE EXTENSION postgis;

CREATE TABLE usuario(
	ID_USUARIO INTEGER PRIMARY KEY,
	email VARCHAR(100),
	password VARCHAR(100),
	rol VARCHAR(50)
);


CREATE TABLE voluntario(
	ID_VOLUNTARIO NUMERIC(8) PRIMARY KEY,
	ID_USUARIO INTEGER,
	nombre VARCHAR(100),
	ubi_vol GEOMETRY(Point, 4326)
);


CREATE TABLE ranking(
	ID_RANKING NUMERIC(8) PRIMARY KEY,
	ID_VOLUNTARIO NUMERIC(8),
	ID_TAREA NUMERIC(8),
	puntaje NUMERIC(3,2),
	flg_invitado NUMERIC(1),
	flg_participa NUMERIC(1)
);


CREATE TABLE institucion(
	ID_INSTITUCION NUMERIC(4) PRIMARY KEY,
	nombre VARCHAR(100),
	descrip VARCHAR(400)
);


CREATE TABLE emergencia(
	ID_EMERGENCIA NUMERIC(6) PRIMARY KEY,
	nombre VARCHAR(100),
	descrip VARCHAR(400),
	fecha_inicio DATE,
	fecha_fin DATE,
	ID_INSTITUCION NUMERIC(4),
	ubi_emer GEOMETRY(Point, 4326)
);


CREATE TABLE habilidad(
	ID_HABILIDAD NUMERIC(4) PRIMARY KEY,
	descrip VARCHAR(100)
);


CREATE TABLE tarea(
	ID_TAREA NUMERIC(8) PRIMARY KEY,
	nombre VARCHAR(60),
	descrip VARCHAR(300),
	fecha_inicio DATE,
	fecha_fin DATE,
	cant_vol_requeridos NUMERIC(4),
	cant_vol_inscritos NUMERIC(4),
	ID_EMERGENCIA NUMERIC(6),
	ID_ESTADO NUMERIC(2)
);


CREATE TABLE vol_habilidad(
	ID_VOL_HAB NUMERIC(8) PRIMARY KEY,
	ID_VOLUNTARIO NUMERIC(8),
	ID_HABILIDAD NUMERIC(8)
);


CREATE TABLE eme_habilidad(
	ID_EME_HAB NUMERIC(8) PRIMARY KEY,
	ID_EMERGENCIA NUMERIC(6),
	ID_HABILIDAD NUMERIC(4)
);

CREATE TABLE tarea_habilidad(
	ID_TARHAB NUMERIC(8) PRIMARY KEY,
	ID_EME_HAB NUMERIC(8),
	ID_TAREA NUMERIC(8)
);


CREATE TABLE estado_tarea(
	ID_ESTADO NUMERIC(2) PRIMARY KEY,
	descrip VARCHAR(20)
);






