CREATE EXTENSION postgis;
CREATE TABLE usuario(
	ID_USUARIO SERIAL PRIMARY KEY,
	email VARCHAR(100),
	password VARCHAR(100),
	rol VARCHAR(50)
);


CREATE TABLE voluntario(
	ID_VOLUNTARIO SERIAL PRIMARY KEY,
	ID_USUARIO INTEGER,
	nombre VARCHAR(100),
	latitud FLOAT,
	longitud FLOAT,
    FOREIGN KEY (ID_USUARIO) REFERENCES usuario(ID_USUARIO)
);

CREATE TABLE institucion(
	ID_INSTITUCION SERIAL PRIMARY KEY,
	nombre VARCHAR(100),
	descrip VARCHAR(400)
);

CREATE TABLE emergencia(
	ID_EMERGENCIA SERIAL PRIMARY KEY,
	nombre VARCHAR(100),
	descrip VARCHAR(400),
	fecha_inicio DATE,
	fecha_fin DATE,
	ID_INSTITUCION INTEGER,
	latitud_emer FLOAT,
	longitud_emer FLOAT,
	estado VARCHAR(15),
    FOREIGN KEY (ID_INSTITUCION) REFERENCES institucion(ID_INSTITUCION)
);

CREATE TABLE estado_tarea(
	ID_ESTADO SERIAL PRIMARY KEY,
	descripcion VARCHAR(20)
);

CREATE TABLE tarea(
	ID_TAREA SERIAL PRIMARY KEY,
	nombre VARCHAR(60),
	descrip VARCHAR(300),
	fecha_inicio DATE,
	fecha_fin DATE,
	cant_vol_requeridos INTEGER,
	cant_vol_inscritos INTEGER,
	ID_EMERGENCIA INTEGER,
	ID_ESTADO INTEGER,
    FOREIGN KEY (ID_EMERGENCIA) REFERENCES emergencia(ID_EMERGENCIA),
    FOREIGN KEY (ID_ESTADO) REFERENCES estado_tarea(ID_ESTADO)
);

CREATE TABLE ranking(
	ID_RANKING SERIAL PRIMARY KEY,
	ID_VOLUNTARIO INTEGER,
	ID_TAREA INTEGER,
	puntaje NUMERIC(3,2),
	flg_invitado INTEGER,
	flg_participa INTEGER,
    FOREIGN KEY (ID_VOLUNTARIO) REFERENCES voluntario(ID_VOLUNTARIO),
    FOREIGN KEY (ID_TAREA) REFERENCES tarea(ID_TAREA)
);

CREATE TABLE habilidad(
	ID_HABILIDAD SERIAL PRIMARY KEY,
	descrip VARCHAR(100)
);

CREATE TABLE vol_habilidad(
	ID_VOL_HAB SERIAL PRIMARY KEY,
	ID_VOLUNTARIO INTEGER,
	ID_HABILIDAD INTEGER,
    FOREIGN KEY (ID_VOLUNTARIO) REFERENCES voluntario(ID_VOLUNTARIO),
    FOREIGN KEY (ID_HABILIDAD) REFERENCES habilidad(ID_HABILIDAD)
);


CREATE TABLE eme_habilidad(
	ID_EME_HAB SERIAL PRIMARY KEY,
	ID_EMERGENCIA INTEGER,
	ID_HABILIDAD INTEGER,
    FOREIGN KEY (ID_EMERGENCIA) REFERENCES emergencia(ID_EMERGENCIA),
    FOREIGN KEY (ID_HABILIDAD) REFERENCES habilidad(ID_HABILIDAD)
);

CREATE TABLE tarea_habilidad(
	ID_TARHAB SERIAL PRIMARY KEY,
	ID_EME_HAB INTEGER,
	ID_TAREA INTEGER,
    FOREIGN KEY (ID_EME_HAB) REFERENCES eme_habilidad(ID_EME_HAB),
    FOREIGN KEY (ID_TAREA) REFERENCES tarea(ID_TAREA)
);
